#  TSP Pure TCL procs for loadlib complemenary procs
#   package tccide_tutorial
#   
proc tclnop {} {
    puts "tclnop ok"
}

proc tcl_test {a b} {# pure tcl proc
    if {$a ne ""} {
        return "TCL TEST OK, \n$a\nResult of 2* $b = [expr $b*2]"
    }
    return [expr $b*2]
}

proc tccide_tutorial_pkgInit {} {
    set ::TCC_COVERSION3 "...tcl aFTER"  
    puts "initialised!"  
}

proc tccide_tutorial_help {} { puts {
# Help Index:
# Generated at 2024-12-06_23-08-13
# Package Index/Loader for tccide_tutorial generated by TSP//TCCIDE Version 20241206-224921

# Compiled Procs 

# ::tspnop 
# ::tspcalltcl 
# ::cnop 
# ::_getsysconfig cvmtaobl
# ::ctest1 text i1
# ::ctest2 text i1
# ::ctest3 text i1
# ::__before_tclinit 
# ::__after_tclinit 

# TCL Procs 

# tclnop 
# tcl_test a b
# tccide_tutorial_pkgInit 
}
}

