# Help Index:
# Generated at 2024-12-27_23-31-53
# Package Index/Loader for tccide_tutorial generated by TSP//TCCIDE Version 20241227-230217

# Compiled Procs 

# ::tspnop 
# ::tspcalltcl 
# ::tspinlinec 
# ::cnop 
# ::_getsysconfig cvmtaobl
# ::_tclstuff_h_ 
# ::ctest1 text i1
# ::ctest2 text i1
# ::ctest3 text i1

# TCL Procs 

# tclnop 
# tcl_test a b
# tccide_tutorial_pkgInit 
# ::tccide_tutorial_help 

proc tccide_tutorial_loadlib {dir packagename} {
     if {[catch {load [file join $dir $packagename[info sharedlibextension]]} err]} {
         source  [file join $dir ${packagename}.tclprocs.tcl]
     }
     source  [file join $dir ${packagename}.puretcl.tcl]
     # call pkgInit procedure to initialise pkg if given
     return [ catch {${packagename}_pkgInit} e] 
}

proc tccide_tutorial_loadext {dir} {
}

#run loader here
tccide_tutorial_loadlib [file dir [info script]] {tccide_tutorial}

